Repository 21TORR/prismic-api, pull requests merged in 2021-11, with the labels that each got.

#8 Add slices, slice zones + proper structure
  src/CustomType/Data/Field/InputField.php
  src/CustomType/Data/PrismicTypeInterface.php
  src/CustomType/Data/Slice/Slice.php
  src/CustomType/Data/Slice/SliceZone.php
  src/CustomType/Data/TypeTab.php
  src/CustomType/Helper/KeyedMapHelper.php
Labels: enhancement

#9 Add all Input fields
  src/CustomType/Data/Field/BooleanField.php
  src/CustomType/Data/Field/ColorField.php
  src/CustomType/Data/Field/DateField.php
  src/CustomType/Data/Field/EmbedField.php
  src/CustomType/Data/Field/GeoPointField.php
  src/CustomType/Data/Field/GroupField.php
  src/CustomType/Data/Field/HeadingField.php
  src/CustomType/Data/Field/ImageField.php
  src/CustomType/Data/Field/InputField.php
  src/CustomType/Data/Field/IntegrationField.php
  src/CustomType/Data/Field/LinkField.php
  src/CustomType/Data/Field/NumberField.php
  src/CustomType/Data/Field/RichTextField.php
  src/CustomType/Data/Field/SelectField.php
  src/CustomType/Data/Field/TextField.php
  src/CustomType/Data/Field/TimestampField.php
  src/CustomType/Data/Field/UidField.php
  src/CustomType/Data/Part/ImageConstraint.php
  src/CustomType/Data/Part/Thumbnail.php
  src/CustomType/Exception/InvalidTypeDefinitionException.php
Labels: enhancement

#10 Several smaller post-release bug fixes
  CHANGELOG.md
  src/Api/PrismicApi.php
  src/CustomType/Data/Field/LinkField.php
  src/CustomType/Data/PrismicTypeInterface.php
Labels: bug, enhancement

#11 Add missing filter for optional fields
  CHANGELOG.md
  src/CustomType/Data/Field/SelectField.php
Labels: bug

#12 Make `Slice` extendable
  CHANGELOG.md
  src/CustomType/Data/Slice/Slice.php
Labels: enhancement

#13 Make custom type `Slice` easier to use
  CHANGELOG.md
  src/CustomType/Data/Slice/Slice.php
Labels: enhancement

#14 Extract `filterOptionalFields` to `FilterFieldsHelper` and add missin…
  CHANGELOG.md
  src/CustomType/Data/Field/BooleanField.php
  src/CustomType/Data/Field/ColorField.php
  src/CustomType/Data/Field/DateField.php
  src/CustomType/Data/Field/EmbedField.php
  src/CustomType/Data/Field/GeoPointField.php
  src/CustomType/Data/Field/GroupField.php
  src/CustomType/Data/Field/ImageField.php
  src/CustomType/Data/Field/InputField.php
  src/CustomType/Data/Field/IntegrationField.php
  src/CustomType/Data/Field/LinkField.php
  src/CustomType/Data/Field/NumberField.php
  src/CustomType/Data/Field/RichTextField.php
  src/CustomType/Data/Field/SelectField.php
  src/CustomType/Data/Field/TextField.php
  src/CustomType/Data/Field/TimestampField.php
  src/CustomType/Data/Field/UidField.php
  src/CustomType/Data/Slice/Slice.php
  src/CustomType/Data/Slice/SliceZone.php
  src/CustomType/Helper/FilterFieldsHelper.php
Labels: bug, enhancement

#15 Add language support for the API client
  CHANGELOG.md
  src/Api/PrismicApi.php
Labels: enhancement

#16 Add languages getter for `Environment`
  CHANGELOG.md
  src/Data/Environment.php
Labels: enhancement

#17 Language is optional again in `PrismicApi::searchDocuments()`
  CHANGELOG.md
  src/Api/PrismicApi.php
Labels: enhancement

#19 Added more integrations of fields + add more structured transformed data
  CHANGELOG.md
  composer.json
  src/Data/Value/DocumentLinkValue.php
  src/Data/Value/ImageValue.php
  src/Data/Value/VideoValue.php
  src/Structure/Field/EmbedField.php
  src/Structure/Field/LinkField.php
  src/Structure/Field/RichTextField.php
  src/Structure/Slice/Slice.php
  src/Validation/SliceValidationCompound.php
Labels: enhancement
